stages:
  - lint
  - build
  - test

variables:
  IMAGE_NAME: "registry.gitlab.com/first_project_group5295348/hive_box_project"

lint:
  stage: lint
  image: python:3.9
  script:
    - pip install pylint
    - pylint app.py

docker-lint:
  stage: lint
  image: hadolint/hadolint
  script:
    - hadolint Dockerfile

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest tests/
